-- ============================================================
-- PROJECT  : Customer Shopping Behavior Analytics
-- AUTHOR   : Data Analytics Portfolio Project
-- DATABASE : MySQL 8.0
-- DATASET  : 3,900 Records | 18 Features
-- OBJECTIVE: Analyze buying patterns and extract actionable
--            business insights from customer purchase data.
-- NOTE     : All queries tested and verified in MySQL Workbench.
--            Any display errors in the downloaded file are due
--            to Workbench connection state, NOT query logic.
-- ============================================================


-- ──────────────────────────────────────────────────────────
-- SETUP
-- ──────────────────────────────────────────────────────────

CREATE DATABASE IF NOT EXISTS customer_behavior_analysis;
USE customer_behavior_analysis;

-- Preview the raw data
SELECT * FROM customer LIMIT 10;


-- ══════════════════════════════════════════════════════════
--   BUSINESS INTELLIGENCE QUERIES
--   Each query answers a specific business question to
--   support data-driven decision-making.
-- ══════════════════════════════════════════════════════════


-- ──────────────────────────────────────────────────────────
-- Q1. What is the total revenue generated by male vs. female customers?
-- BUSINESS USE: Understand gender-based revenue contribution
--               to guide targeted marketing investment.
-- ──────────────────────────────────────────────────────────

SELECT
    gender,
    COUNT(customer_id)            AS total_customers,
    SUM(purchase_amount)          AS total_revenue,
    ROUND(AVG(purchase_amount),2) AS avg_spend
FROM customer
GROUP BY gender
ORDER BY total_revenue DESC;


-- ──────────────────────────────────────────────────────────
-- Q2. Which customers used a discount but still spent more
--     than the average purchase amount?
-- BUSINESS USE: Identify high-value discount users — these
--               customers respond to offers but still spend
--               premium, making them ideal upsell targets.
-- ──────────────────────────────────────────────────────────

SELECT
    customer_id,
    purchase_amount
FROM customer
WHERE discount_applied = 'Yes'
  AND purchase_amount >= (
          SELECT AVG(purchase_amount)
          FROM customer
      )
ORDER BY purchase_amount DESC;


-- ──────────────────────────────────────────────────────────
-- Q3. Which are the top 5 products with the highest average
--     review rating?
-- BUSINESS USE: Identify products with highest customer
--               satisfaction to prioritize in marketing
--               campaigns and featured placements.
-- ──────────────────────────────────────────────────────────

SELECT
    item_purchased,
    ROUND(AVG(review_rating), 2) AS avg_product_rating,
    COUNT(customer_id)           AS total_orders
FROM customer
GROUP BY item_purchased
ORDER BY avg_product_rating DESC
LIMIT 5;


-- ──────────────────────────────────────────────────────────
-- Q4. Compare the average purchase amounts between Standard
--     and Express shipping.
-- BUSINESS USE: Determine if premium shipping correlates
--               with higher spending — informs upselling
--               shipping options at checkout.
-- ──────────────────────────────────────────────────────────

SELECT
    shipping_type,
    COUNT(customer_id)            AS total_orders,
    ROUND(AVG(purchase_amount),2) AS avg_purchase_amount,
    SUM(purchase_amount)          AS total_revenue
FROM customer
WHERE shipping_type IN ('Express', 'Standard')
GROUP BY shipping_type
ORDER BY avg_purchase_amount DESC;


-- ──────────────────────────────────────────────────────────
-- Q5. Do subscribed customers spend more? Compare average
--     spend and total revenue between subscribers and
--     non-subscribers.
-- BUSINESS USE: Evaluate ROI of the subscription program.
--               If subscribers don't outspend, the benefit
--               structure needs to be redesigned.
-- ──────────────────────────────────────────────────────────

SELECT
    subscription_status,
    COUNT(customer_id)            AS total_customers,
    ROUND(AVG(purchase_amount),2) AS avg_spend,
    ROUND(SUM(purchase_amount),2) AS total_revenue
FROM customer
GROUP BY subscription_status
ORDER BY avg_spend DESC;


-- ──────────────────────────────────────────────────────────
-- Q6. Which 5 products have the highest percentage of
--     purchases with discounts applied?
-- BUSINESS USE: Identify over-discounted products where
--               margin is being unnecessarily compressed.
-- ──────────────────────────────────────────────────────────

SELECT
    item_purchased,
    COUNT(customer_id) AS total_orders,
    SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) AS discounted_orders,
    ROUND(
        100.0 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) / COUNT(*),
        2
    ) AS discount_rate_pct
FROM customer
GROUP BY item_purchased
ORDER BY discount_rate_pct DESC
LIMIT 5;


-- ──────────────────────────────────────────────────────────
-- Q7. Segment customers into New, Returning, and Loyal based
--     on their total number of previous purchases, and show
--     the count of each segment.
-- BUSINESS USE: Understand the composition of the customer
--               base. A loyalty-heavy base signals retention
--               strength but acquisition risk.
-- Segments:
--   New       → 1 previous purchase
--   Returning → 2–10 previous purchases
--   Loyal     → 11+ previous purchases
-- ──────────────────────────────────────────────────────────

SELECT
    CASE
        WHEN previous_purchases = 1             THEN 'New'
        WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
        ELSE                                         'Loyal'
    END                 AS customer_segment,
    COUNT(*)            AS number_of_customers,
    ROUND(AVG(purchase_amount),2) AS avg_spend
FROM customer
GROUP BY customer_segment
ORDER BY number_of_customers DESC;


-- ──────────────────────────────────────────────────────────
-- Q8. What are the top 3 most purchased products within
--     each category?
-- BUSINESS USE: Optimize inventory and shelf space by
--               category. Ensures high-demand SKUs are
--               always in stock.
-- TECHNIQUE: DENSE_RANK() window function with PARTITION BY
--            — handles ties correctly, unlike ROW_NUMBER().
-- NOTE: Queries run correctly in MySQL 8.0. Any "errors"
--       in the downloaded file are due to Workbench
--       connection state, not query logic.
-- ──────────────────────────────────────────────────────────

SELECT
    category,
    item_purchased,
    total_orders,
    rank_num
FROM (
    SELECT
        category,
        item_purchased,
        total_orders,
        DENSE_RANK() OVER (
            PARTITION BY category
            ORDER BY total_orders DESC
        ) AS rank_num
    FROM (
        SELECT
            category,
            item_purchased,
            COUNT(customer_id) AS total_orders
        FROM customer
        GROUP BY category, item_purchased
    ) AS aggregated
) AS ranked
WHERE rank_num <= 3
ORDER BY category, rank_num;


-- ──────────────────────────────────────────────────────────
-- Q9. Are customers who are repeat buyers (more than 5
--     previous purchases) also likely to subscribe?
-- BUSINESS USE: Test whether loyalty correlates with
--               subscription uptake — if not, the program
--               is failing to convert its best customers.
-- ──────────────────────────────────────────────────────────

SELECT
    subscription_status,
    COUNT(customer_id)            AS repeat_buyers,
    ROUND(AVG(purchase_amount),2) AS avg_spend
FROM customer
WHERE previous_purchases > 5
GROUP BY subscription_status
ORDER BY repeat_buyers DESC;


-- ──────────────────────────────────────────────────────────
-- Q10. What is the revenue contribution of each age group?
-- BUSINESS USE: Identify the highest-revenue demographic
--               to focus media spend and product development.
-- NOTE: age_group column was engineered in Python (Pandas)
--       during the data cleaning phase before DB loading.
-- ──────────────────────────────────────────────────────────

SELECT
    age_group,
    COUNT(customer_id)            AS total_customers,
    SUM(purchase_amount)          AS total_revenue,
    ROUND(AVG(purchase_amount),2) AS avg_spend,
    ROUND(
        100.0 * SUM(purchase_amount) /
        (SELECT SUM(purchase_amount) FROM customer),
        2
    ) AS revenue_share_pct
FROM customer
GROUP BY age_group
ORDER BY total_revenue DESC;


-- ══════════════════════════════════════════════════════════
-- END OF ANALYSIS
-- Tools Used: Python (Pandas · SQLAlchemy) · MySQL 8.0 · Power BI
-- ══════════════════════════════════════════════════════════
